name: Annapolis_Drinks
favicon: null
layout_spectrum: 0.23046758607961237
typography_spectrum: 0.0994186110328883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6016618087887764
  lightness: 0.0522255334071815
  saturation: 0.30298889544792473
  rhythmicContrast: 0.34098216355778277
purpose: []
